### PR TITLE
Initial commit to migrate project to typescript

### PR DESCRIPTION
**Pull request by mischulz14**
## There are still a few things to fix/discuss:

- [ ] what are the types of the vm/contentVM?
- [ ] what are the types in the backendbinder? 
- [ ] I still have a few tricky type-errors I have ro tackle in the login view and a few other parts of the code

### CODE REVIEW

**Comment by Gleethos** [comment]
Awesome! Nice to see some fresh type safety.
To answer your questions:

> what are the types of the vm/contentVM?

`vm` and `contentVM` are both instances of the `VM` function in the `backend-binder` code.

> what are the types in the backendbinder?

So as I mentioned it uses the `VM` function to represent view models, the `Val` function to represent Javas `Val`property and the `Var` function to represent Javas `Var` property. All of these functions should be turned into proper TypeScript classes so that we have some solid OO for the backend-binder API.

>  I still have a few tricky type-errors I have ro tackle in the login view and a few other parts of the code

Hmm, I haven't checked it out, but let me guess: It complains about things like `vm.username()`, `vm.password()` or `vm.switchToRegister()`, right?

If that is the case then good and bad news:
Good news is that TypeScript is doing a good job with type checking, because 
the mentioned view model methods like `.password()` actually do not exist during runtime.
This is where the bad news are, they are added in the `backend-binder` code during runtime.

Now this is not a dealbreaker, we just need to see how to do dynamic programming in TS and see if we can get away with a boilerplate free solution.
I would suggest that we introduce the declaration of a TS interface for which we create a proxy that does the automatic delegation. So the idea here is that we always have to define a view model API in the frontend which has the same method names as the Java equivalent. What do you think?

**Comment by mischulz14** [comment]
Ok, the current state is the following:
So far I have fixed almost every error in the frontend code apart from the vm issue, which I still don't know the type for. In the backend binder, I managed to solve about half of the problems that the file had, but the other ones are a bit confusing for me. Maybe you can take a look at it and finish typing the backend binder? (:

**Comment by Gleethos** [comment]
Awesome! Well if most errors are fixed I think we can manage the rest of them too.
In the worst case we can just do some type casting in cases where we know the type and be done with it.
I will take a look at it! Thank you for all of the effort. :)

Today I will not manage to take a look at it. But at the weekend I have enough time.

**Comment by Gleethos** [comment]
It is done! We are in TypeScript land :)

I think we can merge this already (after resolving merge conflicts), but I want to do a little cleanup iteration afterwards
under a new ticket, because there is currently still a lot of type declaration madness going on...

**Pull request merged**
