### PR TITLE
Add login view hook

### PR DESCRIPTION
**Pull request by mischulz14**

### CODE REVIEW

**Comment by Gleethos** [comment]
I love the idea of custom hook for our view models, however I was thinking if we could maybe use a more generic approach which can be used for all kinds of views/view model bindings. 
What do you think of this hook:
```js
import { useState } from 'react';

export default function useProperty(vm, propSelector, defaultValue) {

  const [state, setState] = useState(defaultValue);

  if ( vm ) propSelector( vm ).get( v => setState(v) );
  /*
    // So the selector might select something lik this:
    vm.username();
    // And then we bind to the state hooks:
    .get( v => setState(v) );
  */
  return [ state, setState ];
}
```
Which could then be used like so:
```js
import React, { useState } from "react";
import ReactDOM from 'react-dom';
import logo from "../logo.svg";
import useProperty from "../hooks/useProperty.js";

function LoginView({vm}) {
  const [username, setUsername] = useProperty(vm, vm => vm.username(), "");
  const [password, setPassword] = useProperty(vm, vm => vm.password(), "");
  const [feedback, setFeedback] = useProperty(vm, vm => vm.feedback(), "");
  const [feedbackColor, setFeedbackColor] = useProperty(vm, vm => vm.inputValid(), "black");
  return (<div className="row">
            <h1>Login Survivor!</h1>
            <div className="col-6">
              <label>User Name</label>
              <input // Now we use the react state
                  type="text"
                  placeholder="Username"
                  value={username}
                  onkeyup={event => vm.username().set(event.target.value)}
              >
              </input>
            </div>
            <div className="col-6">
              <label>Password</label>
              <input // Now we use the react state
                  type="password"
                  placeholder="Password"
                  value={password}
                  onkeyup={event => vm.password().set(event.target.value)}
              >
              </input>
            </div>
            <div className="col-6">
              <button onClick={() => vm.login()}>Login</button>
            </div>
            <br></br>
            <div className="col-12">
              <label
                  style={{color: feedbackColor, width:90+'%', margin: 1+'em', padding:1+'em', border: 1+'px solid black'}}
                  dangerouslySetInnerHTML={{__html: feedback}}
              >
              </label>
            </div>
        </div>);
}

export default LoginView;
```

I just tested this code and it works.
The only downside I see here is that you have to pass 3 arguments to the new hook which look kinda weird.

**Comment by Gleethos** [comment]
I think we could even go one step further and abstract away things like ` onkeyup={event => vm.username().set(event.target.value)}` where we only have to call `onkeyup={event => setUsername(event.target.value)}` and it would both set the react state AND the view model property, maybe if we have something like this as a state hook:
```js
import { useState } from 'react';

export default function useProperty(vm, propSelector, defaultValue) {

  const [state, setState] = useState(defaultValue);

  if ( vm ) propSelector( vm ).get( v => setState(v) );
  /*
    // So the selector might select something lik this:
    vm.username();
    // And then we bind to the state hooks:
    .get( v => setState(v) );
  */
  const setBothStates = v => {
    setState(v);
    if ( vm ) propSelector( vm ).set( v );
  };

  return [ state, setBothStates ];
}
```
This way we are almost 100% back in pure React land, without having to think about the backend except for when defining the view model state... 

What do you think?

**Comment by mischulz14** [comment]
I implemented the changes and also changed the onkeyup to onChange, which is the default prop that should be used for inputs in React (:
Everything works so far, except the feedback loop

**Comment by Gleethos** [comment]
Looks good!

**Pull request merged**
